// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcddiucedwlnlhfibuss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZGRpdWNlZHdsbmxoZmlidXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzcyNDgsImV4cCI6MjA4NTk1MzI0OH0.ZlXlLH_TOlDJjVAdtkgCsEBv0WF-1MTa0xVQs0kiYbo";

// Import the supabase client like this:
// import { supabase } from "@/shared/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});