import { AssessmentYear, TAX_RELIEF_SOURCE_URL } from "@/features/financial-records/my-tax/domain/taxReliefs";

export interface PlannerSubItem {
  id: string;
  name: string;
  limit: number;
  note?: string;
  perChild?: boolean;
  /** When true the amount is derived automatically from income — user cannot edit it */
  auto?: boolean;
}

export interface PlannerCategory {
  id: string;
  num: number;
  name: string;
  description: string;
  limit: number | null;
  tone: "green" | "blue" | "amber" | "red";
  icon: string;
  subItems: PlannerSubItem[];
}

export interface PlannerReceipt {
  id: string;
  year: AssessmentYear;
  name: string;
  categoryId: string;
  subItemId: string;
  amount: number;
  dataUrl?: string;
}

export const MY_TAX_SOURCE_URL = TAX_RELIEF_SOURCE_URL;

export const MY_TAX_PLANNER_DATA: Record<AssessmentYear, PlannerCategory[]> = {
  "2025": [
    {
      id: "personal",
      num: 1,
      name: "Individual & dependent relatives",
      description: "Automatic personal relief for taxpayer and dependant relatives.",
      limit: 9000,
      tone: "green",
      icon: "User",
      subItems: [{ id: "personal_self", name: "Self and dependent relatives", limit: 9000, note: "Flat relief, no receipt needed.", auto: true }],
    },
    {
      id: "parents",
      num: 2,
      name: "Parents & grandparents care",
      description: "Medical, dental, special needs and carer expenses.",
      limit: 8000,
      tone: "blue",
      icon: "HeartPulse",
      subItems: [
        { id: "parents_medical", name: "Medical, dental, special needs and carer expenses", limit: 8000, note: "Must relate to a condition certified by a medical practitioner." },
        { id: "parents_checkup", name: "Complete medical examination", limit: 1000, note: "Sub-limit RM1,000." },
      ],
    },
    {
      id: "disabled_equipment",
      num: 3,
      name: "Basic supporting equipment",
      description: "Equipment for disabled self, spouse, child or parent.",
      limit: 6000,
      tone: "amber",
      icon: "Accessibility",
      subItems: [{ id: "disabled_equipment_main", name: "Basic supporting equipment purchase", limit: 6000 }],
    },
    {
      id: "disabled_self",
      num: 4,
      name: "Disabled individual",
      description: "Additional relief if the taxpayer is disabled.",
      limit: 7000,
      tone: "blue",
      icon: "BadgeAlert",
      subItems: [{ id: "disabled_self_main", name: "Disabled individual relief", limit: 7000 }],
    },
    {
      id: "education",
      num: 5,
      name: "Education fees (self)",
      description: "Self-education, postgraduate or upskilling courses.",
      limit: 7000,
      tone: "blue",
      icon: "GraduationCap",
      subItems: [
        { id: "education_course", name: "Approved technical, vocational or professional study", limit: 7000 },
        { id: "education_postgrad", name: "Masters or doctorate in any course", limit: 7000 },
        { id: "education_upskill", name: "Upskilling or self-enhancement course", limit: 2000, note: "Sub-limit RM2,000." },
      ],
    },
    {
      id: "medical",
      num: 6,
      name: "Medical expenses",
      description: "Serious disease, fertility, vaccination and dental treatment.",
      limit: 10000,
      tone: "red",
      icon: "Stethoscope",
      subItems: [
        { id: "medical_serious", name: "Serious disease treatment", limit: 10000 },
        { id: "medical_fertility", name: "Fertility treatment", limit: 10000 },
        { id: "medical_vaccination", name: "Vaccination", limit: 1000, note: "Sub-limit RM1,000." },
        { id: "medical_dental", name: "Dental examination and treatment", limit: 1000, note: "Sub-limit RM1,000." },
      ],
    },
    {
      id: "medical_screening",
      num: 7,
      name: "Medical screening & mental health",
      description: "Checkups, test kits, mental health and monitoring devices.",
      limit: 1000,
      tone: "amber",
      icon: "Activity",
      subItems: [
        { id: "screening_checkup", name: "Complete medical examination", limit: 1000 },
        { id: "screening_covid", name: "COVID-19 detection test or self-test kit", limit: 1000 },
        { id: "screening_mental", name: "Mental health examination or consultation", limit: 1000 },
        { id: "screening_monitor", name: "Self-health monitoring equipment", limit: 1000 },
        { id: "screening_detection", name: "Disease detection tests", limit: 1000 },
      ],
    },
    {
      id: "child_intervention",
      num: 8,
      name: "Child intervention (18 and below)",
      description: "Diagnosis and rehabilitation for intellectual disability.",
      limit: 6000,
      tone: "blue",
      icon: "Baby",
      subItems: [
        { id: "child_diagnosis", name: "Assessment of intellectual disability diagnosis", limit: 6000 },
        { id: "child_rehab", name: "Early intervention or rehabilitation treatment", limit: 6000 },
      ],
    },
    {
      id: "lifestyle",
      num: 9,
      name: "Lifestyle",
      description: "Books, internet, devices and personal development.",
      limit: 2500,
      tone: "green",
      icon: "LaptopMinimal",
      subItems: [
        { id: "lifestyle_books", name: "Books, journals, magazines, newspapers or e-subscriptions", limit: 2500 },
        { id: "lifestyle_device", name: "Personal computer, smartphone or tablet", limit: 2500 },
        { id: "lifestyle_internet", name: "Monthly internet subscription under own name", limit: 2500 },
        { id: "lifestyle_courses", name: "Skill improvement or personal development course fee", limit: 2500 },
      ],
    },
    {
      id: "sports",
      num: 10,
      name: "Lifestyle - sports & fitness",
      description: "Sports equipment, facility rental, competition and gym.",
      limit: 1000,
      tone: "green",
      icon: "Dumbbell",
      subItems: [
        { id: "sports_equipment", name: "Sports equipment", limit: 1000 },
        { id: "sports_facility", name: "Rental or entrance fee to sports facility", limit: 1000 },
        { id: "sports_competition", name: "Registration fee for approved sports competition", limit: 1000 },
        { id: "sports_gym", name: "Gym membership or sports training", limit: 1000 },
      ],
    },
    {
      id: "breastfeeding",
      num: 11,
      name: "Breastfeeding equipment",
      description: "For a child aged 2 and below, once every 2 years of assessment.",
      limit: 1000,
      tone: "red",
      icon: "Milk",
      subItems: [{ id: "breastfeeding_main", name: "Breastfeeding equipment", limit: 1000, note: "Allowed once in every two years of assessment." }],
    },
    {
      id: "childcare",
      num: 12,
      name: "Child care fees",
      description: "Registered child care centre or kindergarten for child aged 6 and below.",
      limit: 3000,
      tone: "blue",
      icon: "Blocks",
      subItems: [{ id: "childcare_main", name: "Childcare or kindergarten fees", limit: 3000 }],
    },
    {
      id: "sspn",
      num: 13,
      name: "SSPN net deposit",
      description: "Net deposit in Skim Simpanan Pendidikan Nasional for 2025.",
      limit: 8000,
      tone: "amber",
      icon: "Landmark",
      subItems: [{ id: "sspn_main", name: "Net SSPN deposit", limit: 8000 }],
    },
    {
      id: "spouse",
      num: 14,
      name: "Spouse or alimony",
      description: "Spouse relief or alimony paid to a former wife.",
      limit: 4000,
      tone: "blue",
      icon: "HeartHandshake",
      subItems: [
        { id: "spouse_main", name: "Husband or wife relief", limit: 4000 },
        { id: "spouse_alimony", name: "Alimony payment to former wife", limit: 4000 },
      ],
    },
    {
      id: "disabled_spouse",
      num: 15,
      name: "Disabled spouse",
      description: "Additional relief for disabled husband or wife.",
      limit: 6000,
      tone: "blue",
      icon: "Heart",
      subItems: [{ id: "disabled_spouse_main", name: "Disabled husband or wife", limit: 6000 }],
    },
    {
      id: "children",
      num: 16,
      name: "Children",
      description: "Unmarried child relief by age, disability and education level.",
      limit: null,
      tone: "green",
      icon: "Users",
      subItems: [
        { id: "children_under18", name: "Each child aged under 18", limit: 2000, note: "RM2,000 per child.", perChild: true },
        { id: "children_preu", name: "Each child 18+ in A-Level, certificate or matriculation", limit: 2000, note: "RM2,000 per child.", perChild: true },
        { id: "children_higher", name: "Each child in diploma or higher education", limit: 8000, note: "RM8,000 per child.", perChild: true },
        { id: "children_disabled", name: "Disabled child", limit: 8000, note: "RM8,000 per child.", perChild: true },
        { id: "children_disabled_higher", name: "Disabled child 18+ pursuing diploma or degree", limit: 8000, note: "Additional RM8,000 per child.", perChild: true },
      ],
    },
    {
      id: "insurance",
      num: 17,
      name: "Life insurance & EPF",
      description: "Life insurance premiums and EPF contributions.",
      limit: 7000,
      tone: "amber",
      icon: "Shield",
      subItems: [
        { id: "insurance_epf", name: "Mandatory or voluntary EPF contributions", limit: 4000, note: "Sub-limit RM4,000.", auto: true },
        { id: "insurance_life", name: "Life insurance, family takaful or additional voluntary EPF", limit: 3000, note: "Sub-limit RM3,000." },
      ],
    },
    {
      id: "prs",
      num: 18,
      name: "PRS & deferred annuity",
      description: "Private Retirement Scheme and deferred annuity contributions.",
      limit: 3000,
      tone: "blue",
      icon: "TrendingUp",
      subItems: [{ id: "prs_main", name: "Deferred annuity or PRS contribution", limit: 3000 }],
    },
    {
      id: "education_medical_insurance",
      num: 19,
      name: "Education & medical insurance",
      description: "Insurance premium for education or medical benefit.",
      limit: 4000,
      tone: "blue",
      icon: "FileCheck",
      subItems: [{ id: "education_medical_insurance_main", name: "Education and medical insurance premium", limit: 4000 }],
    },
    {
      id: "socso",
      num: 20,
      name: "SOCSO contribution",
      description: "Social Security Organisation employee contribution.",
      limit: 350,
      tone: "amber",
      icon: "Lock",
      subItems: [{ id: "socso_main", name: "SOCSO contribution", limit: 350, auto: true }],
    },
    {
      id: "ev_compost",
      num: 21,
      name: "EV charging & composting machine",
      description: "Charging facilities for EVs and domestic composting machine.",
      limit: 2500,
      tone: "green",
      icon: "Zap",
      subItems: [
        { id: "ev_charging", name: "EV charging facilities", limit: 2500 },
        { id: "ev_composting", name: "Domestic food waste composting machine", limit: 2500 },
      ],
    },
    {
      id: "housing_loan",
      num: 22,
      name: "First home housing loan interest",
      description: "SPA signed from 1 January 2025 to 31 December 2027.",
      limit: 7000,
      tone: "red",
      icon: "House",
      subItems: [
        { id: "housing_loan_500", name: "House price up to RM500,000", limit: 7000 },
        { id: "housing_loan_750", name: "House price RM500,001 to RM750,000", limit: 5000 },
      ],
    },
  ],
  "2024": [
    {
      id: "personal",
      num: 1,
      name: "Individual & dependent relatives",
      description: "Automatic personal relief for taxpayer and dependant relatives.",
      limit: 9000,
      tone: "green",
      icon: "User",
      subItems: [{ id: "personal_self", name: "Self and dependent relatives", limit: 9000, note: "Flat relief, no receipt needed.", auto: true }],
    },
    {
      id: "parents",
      num: 2,
      name: "Parents care",
      description: "Medical, dental, special needs and carer expenses.",
      limit: 8000,
      tone: "blue",
      icon: "HeartPulse",
      subItems: [
        { id: "parents_medical", name: "Medical, dental, special needs and carer expenses", limit: 8000, note: "Must relate to a condition certified by a medical practitioner." },
        { id: "parents_checkup", name: "Complete medical examination", limit: 1000, note: "Sub-limit RM1,000." },
      ],
    },
    {
      id: "disabled_equipment",
      num: 3,
      name: "Basic supporting equipment",
      description: "Equipment for disabled self, spouse, child or parent.",
      limit: 6000,
      tone: "amber",
      icon: "Accessibility",
      subItems: [{ id: "disabled_equipment_main", name: "Basic supporting equipment purchase", limit: 6000 }],
    },
    {
      id: "disabled_self",
      num: 4,
      name: "Disabled individual",
      description: "Additional relief if the taxpayer is disabled.",
      limit: 6000,
      tone: "blue",
      icon: "BadgeAlert",
      subItems: [{ id: "disabled_self_main", name: "Disabled individual relief", limit: 6000 }],
    },
    {
      id: "education",
      num: 5,
      name: "Education fees (self)",
      description: "Self-education, postgraduate or upskilling courses.",
      limit: 7000,
      tone: "blue",
      icon: "GraduationCap",
      subItems: [
        { id: "education_course", name: "Approved technical, vocational or professional study", limit: 7000 },
        { id: "education_postgrad", name: "Masters or doctorate in any course", limit: 7000 },
        { id: "education_upskill", name: "Upskilling or self-enhancement course", limit: 2000, note: "Sub-limit RM2,000." },
      ],
    },
    {
      id: "medical",
      num: 6,
      name: "Medical expenses",
      description: "Serious disease, fertility, vaccination and dental treatment.",
      limit: 10000,
      tone: "red",
      icon: "Stethoscope",
      subItems: [
        { id: "medical_serious", name: "Serious disease treatment", limit: 10000 },
        { id: "medical_fertility", name: "Fertility treatment", limit: 10000 },
        { id: "medical_vaccination", name: "Vaccination", limit: 1000, note: "Sub-limit RM1,000." },
        { id: "medical_dental", name: "Dental examination and treatment", limit: 1000, note: "Sub-limit RM1,000." },
      ],
    },
    {
      id: "medical_screening",
      num: 7,
      name: "Medical screening & mental health",
      description: "Checkups, test kits and mental health consultations.",
      limit: 1000,
      tone: "amber",
      icon: "Activity",
      subItems: [
        { id: "screening_checkup", name: "Complete medical examination", limit: 1000 },
        { id: "screening_covid", name: "COVID-19 detection test or self-test kit", limit: 1000 },
        { id: "screening_mental", name: "Mental health examination or consultation", limit: 1000 },
      ],
    },
    {
      id: "child_intervention",
      num: 8,
      name: "Child intervention (18 and below)",
      description: "Diagnosis and rehabilitation for intellectual disability.",
      limit: 4000,
      tone: "blue",
      icon: "Baby",
      subItems: [
        { id: "child_diagnosis", name: "Assessment of intellectual disability diagnosis", limit: 4000 },
        { id: "child_rehab", name: "Early intervention or rehabilitation treatment", limit: 4000 },
      ],
    },
    {
      id: "lifestyle",
      num: 9,
      name: "Lifestyle",
      description: "Books, internet, devices and personal development.",
      limit: 2500,
      tone: "green",
      icon: "LaptopMinimal",
      subItems: [
        { id: "lifestyle_books", name: "Books, journals, magazines, newspapers or e-subscriptions", limit: 2500 },
        { id: "lifestyle_device", name: "Personal computer, smartphone or tablet", limit: 2500 },
        { id: "lifestyle_internet", name: "Monthly internet subscription under own name", limit: 2500 },
        { id: "lifestyle_courses", name: "Skill improvement or personal development course fee", limit: 2500 },
      ],
    },
    {
      id: "sports",
      num: 10,
      name: "Lifestyle - sports & fitness",
      description: "Sports equipment, facility rental, competition and gym.",
      limit: 1000,
      tone: "green",
      icon: "Dumbbell",
      subItems: [
        { id: "sports_equipment", name: "Sports equipment", limit: 1000 },
        { id: "sports_facility", name: "Rental or entrance fee to sports facility", limit: 1000 },
        { id: "sports_competition", name: "Registration fee for approved sports competition", limit: 1000 },
        { id: "sports_gym", name: "Gym membership or sports training", limit: 1000 },
      ],
    },
    {
      id: "breastfeeding",
      num: 11,
      name: "Breastfeeding equipment",
      description: "For a child aged 2 and below, once every 2 years of assessment.",
      limit: 1000,
      tone: "red",
      icon: "Milk",
      subItems: [{ id: "breastfeeding_main", name: "Breastfeeding equipment", limit: 1000, note: "Allowed once in every two years of assessment." }],
    },
    {
      id: "childcare",
      num: 12,
      name: "Child care fees",
      description: "Registered child care centre or kindergarten for child aged 6 and below.",
      limit: 3000,
      tone: "blue",
      icon: "Blocks",
      subItems: [{ id: "childcare_main", name: "Childcare or kindergarten fees", limit: 3000 }],
    },
    {
      id: "sspn",
      num: 13,
      name: "SSPN net deposit",
      description: "Net deposit in Skim Simpanan Pendidikan Nasional for 2024.",
      limit: 8000,
      tone: "amber",
      icon: "Landmark",
      subItems: [{ id: "sspn_main", name: "Net SSPN deposit", limit: 8000 }],
    },
    {
      id: "spouse",
      num: 14,
      name: "Spouse or alimony",
      description: "Spouse relief or alimony paid to a former wife.",
      limit: 4000,
      tone: "blue",
      icon: "HeartHandshake",
      subItems: [
        { id: "spouse_main", name: "Husband or wife relief", limit: 4000 },
        { id: "spouse_alimony", name: "Alimony payment to former wife", limit: 4000 },
      ],
    },
    {
      id: "disabled_spouse",
      num: 15,
      name: "Disabled spouse",
      description: "Additional relief for disabled husband or wife.",
      limit: 5000,
      tone: "blue",
      icon: "Heart",
      subItems: [{ id: "disabled_spouse_main", name: "Disabled husband or wife", limit: 5000 }],
    },
    {
      id: "children",
      num: 16,
      name: "Children",
      description: "Unmarried child relief by age, disability and education level.",
      limit: null,
      tone: "green",
      icon: "Users",
      subItems: [
        { id: "children_under18", name: "Each child aged under 18", limit: 2000, note: "RM2,000 per child.", perChild: true },
        { id: "children_preu", name: "Each child 18+ in A-Level, certificate or matriculation", limit: 2000, note: "RM2,000 per child.", perChild: true },
        { id: "children_higher", name: "Each child in diploma or higher education", limit: 8000, note: "RM8,000 per child.", perChild: true },
        { id: "children_disabled", name: "Disabled child", limit: 6000, note: "RM6,000 per child.", perChild: true },
        { id: "children_disabled_higher", name: "Disabled child 18+ pursuing diploma or degree", limit: 8000, note: "Additional RM8,000 per child.", perChild: true },
      ],
    },
    {
      id: "insurance",
      num: 17,
      name: "Life insurance & EPF",
      description: "Life insurance premiums and EPF contributions.",
      limit: 7000,
      tone: "amber",
      icon: "Shield",
      subItems: [
        { id: "insurance_epf", name: "Mandatory or voluntary EPF contributions", limit: 4000, note: "Sub-limit RM4,000.", auto: true },
        { id: "insurance_life", name: "Life insurance, family takaful or additional voluntary EPF", limit: 3000, note: "Sub-limit RM3,000." },
      ],
    },
    {
      id: "prs",
      num: 18,
      name: "PRS & deferred annuity",
      description: "Private Retirement Scheme and deferred annuity contributions.",
      limit: 3000,
      tone: "blue",
      icon: "TrendingUp",
      subItems: [{ id: "prs_main", name: "Deferred annuity or PRS contribution", limit: 3000 }],
    },
    {
      id: "education_medical_insurance",
      num: 19,
      name: "Education & medical insurance",
      description: "Insurance premium for education or medical benefit.",
      limit: 3000,
      tone: "blue",
      icon: "FileCheck",
      subItems: [{ id: "education_medical_insurance_main", name: "Education and medical insurance premium", limit: 3000 }],
    },
    {
      id: "socso",
      num: 20,
      name: "SOCSO contribution",
      description: "Social Security Organisation employee contribution.",
      limit: 350,
      tone: "amber",
      icon: "Lock",
      subItems: [{ id: "socso_main", name: "SOCSO contribution", limit: 350, auto: true }],
    },
    {
      id: "ev",
      num: 21,
      name: "EV charging facilities",
      description: "Charging facilities for electric vehicles.",
      limit: 2500,
      tone: "green",
      icon: "Zap",
      subItems: [{ id: "ev_charging", name: "EV charging facilities", limit: 2500 }],
    },
  ],
};

export const DETECTION_KEYWORD_MAP: Array<{ keys: string[]; subItemId: string }> = [
  { keys: ["klinik", "clinic", "hospital", "doktor", "doctor", "pharmacy", "farmasi"], subItemId: "parents_medical" },
  { keys: ["dental", "dentist", "gigi"], subItemId: "medical_dental" },
  { keys: ["vaccine", "vaccination", "vaksin"], subItemId: "medical_vaccination" },
  { keys: ["checkup", "check-up", "medical exam", "screening"], subItemId: "screening_checkup" },
  { keys: ["mental", "therapy", "therapist", "psych"], subItemId: "screening_mental" },
  { keys: ["covid", "antigen", "pcr"], subItemId: "screening_covid" },
  { keys: ["course", "kursus", "training", "upskill", "certificate", "diploma", "degree", "master", "university", "college"], subItemId: "education_upskill" },
  { keys: ["book", "buku", "journal", "magazine", "newspaper"], subItemId: "lifestyle_books" },
  { keys: ["laptop", "computer", "tablet", "smartphone", "phone", "pc"], subItemId: "lifestyle_device" },
  { keys: ["internet", "wifi", "unifi", "maxis", "celcom", "digi"], subItemId: "lifestyle_internet" },
  { keys: ["gym", "fitness", "badminton", "futsal", "sports"], subItemId: "sports_gym" },
  { keys: ["nursery", "childcare", "kindergarten", "tadika"], subItemId: "childcare_main" },
  { keys: ["insurance", "takaful", "premium"], subItemId: "insurance_life" },
  { keys: ["epf", "kwsp"], subItemId: "insurance_epf" },
  { keys: ["socso", "perkeso"], subItemId: "socso_main" },
  { keys: ["sspn"], subItemId: "sspn_main" },
  { keys: ["charger", "charging", "ev"], subItemId: "ev_charging" },
  { keys: ["compost"], subItemId: "ev_composting" },
  { keys: ["home loan", "housing", "mortgage"], subItemId: "housing_loan_500" },
];

export const DEFAULT_FALLBACKS = [
  "parents_medical",
  "lifestyle_device",
  "lifestyle_internet",
  "education_upskill",
  "insurance_life",
  "childcare_main",
];
