export type AssessmentYear = string;

export interface TaxRelief {
  id: string;
  section: string;
  order: number;
  title: string;
  amountLabel: string;
  maxClaimAmount: number;
  summary: string;
  details?: string[];
  note?: string;
}

export const TAX_RELIEF_SOURCE_URL =
  "https://www.hasil.gov.my/en/individual/individual-life-cycle/income-declaration/tax-reliefs/";

export const TAX_RELIEFS_BY_YEAR: Record<AssessmentYear, TaxRelief[]> = {
  "2025": [
    {
      id: "individual-dependent-relatives",
      section: "Personal",
      order: 1,
      title: "Individual and dependent relatives",
      amountLabel: "RM9,000",
      maxClaimAmount: 9000,
      summary: "Automatic personal relief for the taxpayer and dependent relatives.",
    },
    {
      id: "parents-grandparents-care",
      section: "Health & Care",
      order: 2,
      title: "Parents and grandparents care expenses",
      amountLabel: "Up to RM8,000",
      maxClaimAmount: 8000,
      summary: "Medical, dental, special needs and carer expenses for parents or grandparents.",
      details: [
        "Medical treatment, dental treatment, special needs and carer expenses must relate to a condition certified by a medical practitioner.",
        "Complete medical examination is included but restricted to RM1,000.",
      ],
    },
    {
      id: "disabled-support-equipment",
      section: "Health & Care",
      order: 3,
      title: "Basic supporting equipment for disabled family members",
      amountLabel: "Up to RM6,000",
      maxClaimAmount: 6000,
      summary: "Equipment purchased for disabled self, spouse, child or parent.",
    },
    {
      id: "disabled-individual",
      section: "Personal",
      order: 4,
      title: "Disabled individual",
      amountLabel: "RM7,000",
      maxClaimAmount: 7000,
      summary: "Additional relief if the taxpayer is a disabled individual.",
    },
    {
      id: "self-education",
      section: "Personal",
      order: 5,
      title: "Education fees (self)",
      amountLabel: "Up to RM7,000",
      maxClaimAmount: 7000,
      summary: "Approved self-education, postgraduate or upskilling courses.",
      details: [
        "Includes technical, vocational, industrial, scientific, technological, legal, accounting and Islamic financing courses.",
        "Masters or doctorate level covers any course of study.",
        "Upskilling or self-enhancement courses are restricted to RM2,000.",
      ],
    },
    {
      id: "medical-serious-disease",
      section: "Health & Care",
      order: 6,
      title: "Serious disease, fertility, vaccination and dental treatment",
      amountLabel: "Up to RM10,000",
      maxClaimAmount: 10000,
      summary: "Medical expenses for self, spouse or child.",
      details: [
        "Includes serious diseases and fertility treatment.",
        "Vaccination is restricted to RM1,000.",
        "Dental examination and treatment is restricted to RM1,000.",
      ],
    },
    {
      id: "preventive-health",
      section: "Health & Care",
      order: 7,
      title: "Preventive health and screenings",
      amountLabel: "Up to RM1,000",
      maxClaimAmount: 1000,
      summary: "Medical examination, mental health checks, self-test kits and monitoring devices.",
      details: [
        "Includes complete medical examination for self, spouse or child.",
        "Includes COVID-19 detection tests and self-detection kits.",
        "Includes mental health examination or consultation, self-health monitoring equipment and disease detection test fees.",
      ],
    },
    {
      id: "child-development-assessment",
      section: "Family",
      order: 8,
      title: "Assessment and intervention for child aged 18 and below",
      amountLabel: "Up to RM6,000",
      maxClaimAmount: 6000,
      summary: "Assessment of intellectual disability diagnosis and early intervention or rehabilitation treatment.",
    },
    {
      id: "lifestyle-general",
      section: "Lifestyle",
      order: 9,
      title: "Lifestyle expenses",
      amountLabel: "Up to RM2,500",
      maxClaimAmount: 2500,
      summary: "Books, devices, internet and personal development expenses for self, spouse or child.",
      details: [
        "Includes books, journals, magazines, newspapers and similar publications that are not banned.",
        "Includes personal computer, smartphone or tablet not used for business.",
        "Includes internet subscription under the taxpayer's own name and skill improvement or personal development courses.",
      ],
    },
    {
      id: "lifestyle-sports",
      section: "Lifestyle",
      order: 10,
      title: "Additional sports and fitness lifestyle relief",
      amountLabel: "Up to RM1,000",
      maxClaimAmount: 1000,
      summary: "Sports equipment, sports facility fees, approved competition fees, gym memberships and sports training.",
    },
    {
      id: "breastfeeding-equipment",
      section: "Family",
      order: 11,
      title: "Breastfeeding equipment",
      amountLabel: "Up to RM1,000",
      maxClaimAmount: 1000,
      summary: "Equipment for a child aged 2 and below.",
      note: "Allowed once in every two years of assessment.",
    },
    {
      id: "child-care-fees",
      section: "Family",
      order: 12,
      title: "Child care and kindergarten fees",
      amountLabel: "Up to RM3,000",
      maxClaimAmount: 3000,
      summary: "Fees paid to a registered child care centre or kindergarten for a child aged 6 and below.",
    },
    {
      id: "sspn",
      section: "Family",
      order: 13,
      title: "Net SSPN savings deposit",
      amountLabel: "Up to RM8,000",
      maxClaimAmount: 8000,
      summary: "Net deposit in Skim Simpanan Pendidikan Nasional for Year of Assessment 2025.",
    },
    {
      id: "spouse-alimony",
      section: "Family",
      order: 14,
      title: "Spouse or alimony to former wife",
      amountLabel: "Up to RM4,000",
      maxClaimAmount: 4000,
      summary: "Relief for spouse or alimony payments to a former wife.",
    },
    {
      id: "disabled-spouse",
      section: "Family",
      order: 15,
      title: "Disabled spouse",
      amountLabel: "RM6,000",
      maxClaimAmount: 6000,
      summary: "Additional relief if the spouse is disabled.",
    },
    {
      id: "child-under-18",
      section: "Family",
      order: 16,
      title: "Each unmarried child below 18",
      amountLabel: "RM2,000 per child",
      maxClaimAmount: 2000,
      summary: "Per-child relief for each unmarried child under 18 years old.",
      note: "Enter the claim for one child per line item in this planner or total it manually outside the tool if you have multiple children.",
    },
    {
      id: "child-over-18-pre-u",
      section: "Family",
      order: 17,
      title: "Each unmarried child 18 and above in full-time pre-university education",
      amountLabel: "RM2,000 per child",
      maxClaimAmount: 2000,
      summary: "Covers A-Level, certificate, matriculation or preparatory courses.",
    },
    {
      id: "child-higher-education",
      section: "Family",
      order: 18,
      title: "Each unmarried child in diploma or higher education",
      amountLabel: "RM8,000 per child",
      maxClaimAmount: 8000,
      summary: "For approved diploma and above in Malaysia or degree and above overseas.",
    },
    {
      id: "disabled-child",
      section: "Family",
      order: 19,
      title: "Disabled child",
      amountLabel: "RM8,000",
      maxClaimAmount: 8000,
      summary: "Additional relief for a disabled child.",
      note: "HASiL also notes a further RM8,000 in specific study situations for a disabled child aged 18 and above. That extra amount is not auto-added in this planner.",
    },
    {
      id: "life-insurance-epf",
      section: "Protection & Savings",
      order: 20,
      title: "Life insurance and EPF",
      amountLabel: "Up to RM7,000",
      maxClaimAmount: 7000,
      summary: "EPF, approved pension schemes, life insurance, family takaful and additional voluntary EPF contributions.",
      details: [
        "EPF or approved scheme contributions are restricted to RM4,000.",
        "Life insurance, family takaful or additional voluntary EPF contributions are restricted to RM3,000.",
      ],
    },
    {
      id: "prs-annuity",
      section: "Protection & Savings",
      order: 21,
      title: "Deferred annuity and private retirement scheme",
      amountLabel: "Up to RM3,000",
      maxClaimAmount: 3000,
      summary: "Relief for deferred annuity and PRS contributions.",
    },
    {
      id: "education-medical-insurance",
      section: "Protection & Savings",
      order: 22,
      title: "Education and medical insurance",
      amountLabel: "Up to RM4,000",
      maxClaimAmount: 4000,
      summary: "Insurance premiums for education and medical coverage.",
    },
    {
      id: "socso",
      section: "Protection & Savings",
      order: 23,
      title: "SOCSO contribution",
      amountLabel: "Up to RM350",
      maxClaimAmount: 350,
      summary: "Contribution to the Social Security Organization.",
    },
    {
      id: "ev-compost",
      section: "Green & Housing",
      order: 24,
      title: "EV charging facilities and domestic composting machine",
      amountLabel: "Up to RM2,500",
      maxClaimAmount: 2500,
      summary: "Expenses on EV charging facilities and domestic food waste composting machines for non-business use.",
    },
    {
      id: "first-home-interest",
      section: "Green & Housing",
      order: 25,
      title: "Housing loan interest for first home ownership",
      amountLabel: "Up to RM7,000 or RM5,000",
      maxClaimAmount: 7000,
      summary: "Interest paid for first home ownership where the sale and purchase agreement is dated from 1 January 2025 to 31 December 2027.",
      details: [
        "Residential house price up to RM500,000 has a relief limit of RM7,000.",
        "Residential house price above RM500,000 and up to RM750,000 has a relief limit of RM5,000.",
      ],
      note: "This planner caps the field at RM7,000. If your property falls in the RM5,000 bracket, enter the lower amount manually.",
    },
  ],
  "2024": [
    {
      id: "individual-dependent-relatives",
      section: "Personal",
      order: 1,
      title: "Individual and dependent relatives",
      amountLabel: "RM9,000",
      maxClaimAmount: 9000,
      summary: "Automatic personal relief for the taxpayer and dependent relatives.",
    },
    {
      id: "parents-care",
      section: "Health & Care",
      order: 2,
      title: "Parents care expenses",
      amountLabel: "Up to RM8,000",
      maxClaimAmount: 8000,
      summary: "Medical, dental, special needs and carer expenses for parents.",
      details: [
        "Medical treatment, dental treatment, special needs and carer expenses must relate to a condition certified by a medical practitioner.",
        "Complete medical examination is included but restricted to RM1,000.",
      ],
    },
    {
      id: "disabled-support-equipment",
      section: "Health & Care",
      order: 3,
      title: "Basic supporting equipment for disabled family members",
      amountLabel: "Up to RM6,000",
      maxClaimAmount: 6000,
      summary: "Equipment purchased for disabled self, spouse, child or parent.",
    },
    {
      id: "disabled-individual",
      section: "Personal",
      order: 4,
      title: "Disabled individual",
      amountLabel: "RM6,000",
      maxClaimAmount: 6000,
      summary: "Additional relief if the taxpayer is a disabled individual.",
    },
    {
      id: "self-education",
      section: "Personal",
      order: 5,
      title: "Education fees (self)",
      amountLabel: "Up to RM7,000",
      maxClaimAmount: 7000,
      summary: "Approved self-education, postgraduate or upskilling courses.",
      details: [
        "Includes technical, vocational, industrial, scientific, technological, legal, accounting and Islamic financing courses.",
        "Masters or doctorate level covers any course of study.",
        "Upskilling or self-enhancement courses are restricted to RM2,000.",
      ],
    },
    {
      id: "medical-serious-disease",
      section: "Health & Care",
      order: 6,
      title: "Serious disease, fertility, vaccination and dental treatment",
      amountLabel: "Up to RM10,000",
      maxClaimAmount: 10000,
      summary: "Medical expenses for self, spouse or child.",
      details: [
        "Includes serious diseases and fertility treatment.",
        "Vaccination is restricted to RM1,000.",
        "Dental examination and treatment is restricted to RM1,000.",
      ],
    },
    {
      id: "preventive-health",
      section: "Health & Care",
      order: 7,
      title: "Preventive health and screenings",
      amountLabel: "Up to RM1,000",
      maxClaimAmount: 1000,
      summary: "Medical examination, COVID-19 tests and mental health checks.",
      details: [
        "Includes complete medical examination for self, spouse or child.",
        "Includes COVID-19 detection tests and self-detection kits.",
        "Includes mental health examination or consultation.",
      ],
    },
    {
      id: "child-development-assessment",
      section: "Family",
      order: 8,
      title: "Assessment and intervention for child aged 18 and below",
      amountLabel: "Up to RM4,000",
      maxClaimAmount: 4000,
      summary: "Assessment of intellectual disability diagnosis and early intervention or rehabilitation treatment.",
    },
    {
      id: "lifestyle-general",
      section: "Lifestyle",
      order: 9,
      title: "Lifestyle expenses",
      amountLabel: "Up to RM2,500",
      maxClaimAmount: 2500,
      summary: "Books, devices, internet and personal development expenses for self, spouse or child.",
      details: [
        "Includes books, journals, magazines, newspapers and similar publications that are not banned.",
        "Includes personal computer, smartphone or tablet not used for business.",
        "Includes internet subscription under the taxpayer's own name and skill improvement or personal development courses.",
      ],
    },
    {
      id: "lifestyle-sports",
      section: "Lifestyle",
      order: 10,
      title: "Additional sports and fitness lifestyle relief",
      amountLabel: "Up to RM1,000",
      maxClaimAmount: 1000,
      summary: "Sports equipment, sports facility fees, approved competition fees, gym memberships and sports training.",
    },
    {
      id: "breastfeeding-equipment",
      section: "Family",
      order: 11,
      title: "Breastfeeding equipment",
      amountLabel: "Up to RM1,000",
      maxClaimAmount: 1000,
      summary: "Equipment for a child aged 2 and below.",
      note: "Allowed once in every two years of assessment.",
    },
    {
      id: "child-care-fees",
      section: "Family",
      order: 12,
      title: "Child care and kindergarten fees",
      amountLabel: "Up to RM3,000",
      maxClaimAmount: 3000,
      summary: "Fees paid to a registered child care centre or kindergarten for a child aged 6 and below.",
    },
    {
      id: "sspn",
      section: "Family",
      order: 13,
      title: "Net SSPN savings deposit",
      amountLabel: "Up to RM8,000",
      maxClaimAmount: 8000,
      summary: "Net deposit in Skim Simpanan Pendidikan Nasional for Year of Assessment 2024.",
    },
    {
      id: "spouse-alimony",
      section: "Family",
      order: 14,
      title: "Spouse or alimony to former wife",
      amountLabel: "Up to RM4,000",
      maxClaimAmount: 4000,
      summary: "Relief for spouse or alimony payments to a former wife.",
    },
    {
      id: "disabled-spouse",
      section: "Family",
      order: 15,
      title: "Disabled spouse",
      amountLabel: "RM5,000",
      maxClaimAmount: 5000,
      summary: "Additional relief if the spouse is disabled.",
    },
    {
      id: "child-under-18",
      section: "Family",
      order: 16,
      title: "Each unmarried child below 18",
      amountLabel: "RM2,000 per child",
      maxClaimAmount: 2000,
      summary: "Per-child relief for each unmarried child under 18 years old.",
      note: "Enter the claim for one child per line item in this planner or total it manually outside the tool if you have multiple children.",
    },
    {
      id: "child-over-18-pre-u",
      section: "Family",
      order: 17,
      title: "Each unmarried child 18 and above in full-time pre-university education",
      amountLabel: "RM2,000 per child",
      maxClaimAmount: 2000,
      summary: "Covers A-Level, certificate, matriculation or preparatory courses.",
    },
    {
      id: "child-higher-education",
      section: "Family",
      order: 18,
      title: "Each unmarried child in diploma or higher education",
      amountLabel: "RM8,000 per child",
      maxClaimAmount: 8000,
      summary: "For approved diploma and above in Malaysia or degree and above overseas.",
    },
    {
      id: "disabled-child",
      section: "Family",
      order: 19,
      title: "Disabled child",
      amountLabel: "RM6,000",
      maxClaimAmount: 6000,
      summary: "Additional relief for a disabled child.",
      note: "HASiL also notes a further RM8,000 in specific study situations for a disabled child aged 18 and above. That extra amount is not auto-added in this planner.",
    },
    {
      id: "life-insurance-epf",
      section: "Protection & Savings",
      order: 20,
      title: "Life insurance and EPF",
      amountLabel: "Up to RM7,000",
      maxClaimAmount: 7000,
      summary: "EPF, approved pension schemes, life insurance, family takaful and additional voluntary EPF contributions.",
      details: [
        "EPF or approved scheme contributions are restricted to RM4,000.",
        "Life insurance, family takaful or additional voluntary EPF contributions are restricted to RM3,000.",
      ],
    },
    {
      id: "prs-annuity",
      section: "Protection & Savings",
      order: 21,
      title: "Deferred annuity and private retirement scheme",
      amountLabel: "Up to RM3,000",
      maxClaimAmount: 3000,
      summary: "Relief for deferred annuity and PRS contributions.",
    },
    {
      id: "education-medical-insurance",
      section: "Protection & Savings",
      order: 22,
      title: "Education and medical insurance",
      amountLabel: "Up to RM3,000",
      maxClaimAmount: 3000,
      summary: "Insurance premiums for education and medical coverage.",
    },
    {
      id: "socso",
      section: "Protection & Savings",
      order: 23,
      title: "SOCSO contribution",
      amountLabel: "Up to RM350",
      maxClaimAmount: 350,
      summary: "Contribution to the Social Security Organization.",
    },
    {
      id: "ev-charging",
      section: "Green & Housing",
      order: 24,
      title: "EV charging facilities",
      amountLabel: "Up to RM2,500",
      maxClaimAmount: 2500,
      summary: "Expenses on EV charging facilities for non-business use.",
    },
  ],
};

export const TAX_RELIEF_SECTIONS = [
  "Personal",
  "Health & Care",
  "Lifestyle",
  "Family",
  "Protection & Savings",
  "Green & Housing",
] as const;

export const getTaxReliefsForYear = (year: string): TaxRelief[] => {
  return TAX_RELIEFS_BY_YEAR[year] || TAX_RELIEFS_BY_YEAR[Object.keys(TAX_RELIEFS_BY_YEAR).sort().reverse()[0]];
};
